config/routes.rb
Rails.application.routes.draw do

  resources :shows
	root 'actors#index'
	
	resources :actors
	resources :movies
	
end

app/models/actor.rb
class Actor < ActiveRecord::Base
	
	belongs_to :collection
	has_many :studios
	has_many :televisions
	has_many :movies, through: :studios
	has_many :shows, through: :televisions
	accepts_nested_attributes_for :movies
	accepts_nested_attributes_for :shows
	
	validates :name,
						uniqueness: true
						
end

app/models/movie.rb
class Movie < ActiveRecord::Base

	has_many :studios
	has_many :actors, through: :studios
	accepts_nested_attributes_for :actors,
																reject_if: proc { |attributes| attributes['name'].blank? },
																allow_destroy: true
	
end

app/models/show.rb
class Show < ActiveRecord::Base
	
	has_many :televisions
	has_many :actors, through: :televisions
	
	accepts_nested_attributes_for :actors,
																reject_if: proc { |attributes| attributes['name'].blank? },
																allow_destroy: true
	
end

app/models/studio.rb
class Studio < ActiveRecord::Base
	belongs_to :movie
	belongs_to :actor
end

app/models/television.rb
class Television < ActiveRecord::Base
	
	belongs_to :actor
	belongs_to :show
	
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
	
  def index
		@actors = Actor.all.order("name")
  end
  
  def show
	  @actor = Actor.find(params[:id])
	  @movies = @actor.movies
	 end
  
  def new
	  @actor = Actor.new
	end
	
	def create
		@actor = Actor.new(actor_params)
		@actor.save
		redirect_to @actor
	end
	
	def edit
		@actor = Actor.find(params[:id])
		@movies = @actor.movies
	end
	
	def update
		@actor = Actor.find(params[:id])
		@actor.update(actor_params)
		if @actor.save
			redirect_to @actor
		else
			render :edit
		end
	end
	
	def destroy
		@actor = Actor.find(params[:id]).destroy
		redirect_to root_path
	end
	
	private
	
	def actor_params
		params.require(:actor).permit(:name, :image, :imdb)	
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	
  def index
	  @movies = Movie.all.order("title")
  end

  def show
	  @movie = Movie.find(params[:id])
	  @actors = @movie.actors
  end
  
  def new
	  @movie = Movie.new
	  @movie.actors.build
	  @all_actors = Actor.all.order('name')
  end

  def create
	  @movie = Movie.new(movie_params)
	  params[:actors][:id].each do |actor|
			if !actor.empty?
				@movie.studios.build(:actor_id => actor)	
			end
		end
	  @movie.save
	  redirect_to @movie
  end

  def edit
	  @movie = Movie.find(params[:id])
	  @actors = @movie.actors
	  @movie.actors.build
  end

  def update
	  @movie = Movie.find(params[:id])
	  @movie.update(movie_params)
	  if @movie.save
			redirect_to @movie
		else
		  render :edit
		end
  end

  def destroy
	  @movie = Movie.find(params[:id]).destroy
	  redirect_to root_path
  end
  
  private
  
  def movie_params
		params.require(:movie).permit(:title, :image, :description, :rating, :genre, :year, actors_attributes: [:id, :name, :_destroy])  
	end
  
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
	
	def index
		@shows = Show.all.order('name')
	end
	
	def show
		@show = Show.find(params[:id])
		@actors = @show.actors
	end
	
	def edit
	  @show = Show.find(params[:id])
	  @actors = @show.actors
	  @show.actors.build
  end

  def update
	  @show = Show.find(params[:id])
	  @show.update(show_params)
	  if @show.save
			redirect_to @show
		else
		  render :edit
		end
  end
	
	def new
		@show = Show.new
		@show.actors.build
		@all_actors = Actor.all.order('name')
	end
	
	def create
		@show = Show.new(show_params)
		params[:actors][:id].each do |actor|
			if !actor.empty?
				@show.televisions.build(:actor_id => actor)	
			end
		end

		if @show.save
			redirect_to @show
		else
			render :new
		end
	end
	
	def destroy
		@show = Show.find(params[:id]).destroy
		redirect_to movie_path
	end
	
	private
	
	def show_params
		params.require(:show).permit(:name, :description, :rating, :image, :genre, actors_attributes: [:id, :name, :_destroy])
	end

end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/actors/edit.html.erb
<h2>Editing <%= @actor.name %></h2>

<%= form_for @actor do |f| %>

	<%= f.label :name %>
	<%= f.text_field :name %>
	
	<%= f.label :image %>
	<%= f.text_field :image %>
	
	<%= f.label :imdb %>
	<%= f.text_field :imdb %>
	

	
	<%= f.submit %>

<% end %>

app/views/actors/index.html.erb
<h1>Actors</h1>
<%= link_to "New Actor Entry", new_actor_path, class: 'btn btn-primary' %>

<div style="height:30px;"></div>

<div class="row">
<% @actors.each do |a| %>

		<div class="col-sm-6 col-md-3">
			<div class="thumbnail">
				<%= link_to image_tag(a.image), a %>
				<div class="caption">
					<h3 class="center"><%= link_to a.name, a %></h3>
					<p class="imdb"><%= link_to image_tag('http://vignette1.wikia.nocookie.net/planetterror/images/5/55/Imdb.png/revision/latest?cb=20140627161116'), a.imdb %></p>
				
				</div>
			</div>
		</div>

<% end %>
</div>

app/views/actors/new.html.erb
New Actor

<%= form_for @actor do |f| %>

	<%= f.label :name %>
	<%= f.text_field :name %>
	
	<%= f.label :image %>
	<%= f.text_field :image %>
	
	<%= f.label :imdb %>
	<%= f.text_field :imdb %>
	

	
	<%= f.submit %>

<% end %>

app/views/actors/show.html.erb
<%= image_tag(@actor.image) %> 
<h2><%= @actor.name %></h2>
<p><%= link_to image_tag('http://vignette1.wikia.nocookie.net/planetterror/images/5/55/Imdb.png/revision/latest?cb=20140627161116'), @actor.imdb %></p>



<% if @movies.any? %>
	<% @movies.each do |m| %>
		<%= link_to m.title, m %>
	<% end %>
<% end %>


<p><%= link_to 'Edit', edit_actor_path, class: 'btn btn-info' %></p>
<p><%= link_to "All Actors", root_path, class: 'btn btn-primary' %></p>
<p><%= link_to "Delete Actor", actor_path(@actor), method: :delete, data: { confirm: "You really wanna do that huh?" }, class: 'btn btn-danger' %></p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Addicted</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Movies', movies_path %></li>
        <li><%= link_to 'Tv', shows_path %></li>
        <li><%= link_to 'Actors', actors_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Addicted</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
<%= render 'layouts/header' %>

<div class="container">
	
	<%= yield %>

</div>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/movies/edit.html.erb
<h2>Editing <%= @movie.title %></h2>

<%= form_for @movie do |f| %>

	<%= f.label :image %>
	<%= f.text_field :image %>
	
	<%= f.label :title %>
	<%= f.text_field :title %>
	
	<%= f.label :description %>
	<%= f.text_field :description %>
	
	<%= f.label :rating %>
	<%= f.text_field :rating %>
	
	<%= f.label :genre %>
	<%= f.text_field :genre %>
	
	<%= f.label :year %>
	<%= f.text_field :year %><br><br>
	
	<%= f.fields_for :actors do |a| %>
		<%= a.text_field :name %>
		<%= a.check_box :_destroy %>
		<%= a.label :_destroy, 'remove' %><br>
	<% end %>
	
	<%= f.submit %>

<% end %>

app/views/movies/index.html.erb
<h1>Movies</h1>
<%= link_to "New Movie Entry", new_movie_path, class: 'btn btn-primary' %>

<div style="height:30px;"></div>

<div class="row">
<% @movies.each do |m| %>

		<div class="col-sm-6 col-md-3">
			<div class="thumbnail">
				<%= link_to image_tag(m.image), m %>
				<div class="caption">
					<% link_to m.title, m %>
					<% m.actors.each do |a| %>
						<% link_to a.name, a %>
					<% end %>
					<p></p>
				</div>
			</div>
		</div>

<% end %>
</div>

app/views/movies/new.html.erb
<h1>Movies#new</h1>
<p>Find me in app/views/movies/new.html.erb</p>

<%= form_for @movie do |f| %>
	<%= f.label :image %>
	<%= f.text_field :image %>
	
	<%= f.label :title %>
	<%= f.text_field :title %>
	
	<%= f.label :description %>
	<%= f.text_field :description %>
	
	<%= f.label :rating %>
	<%= f.text_field :rating %>
	
	<%= f.label :genre %>
	<%= f.text_field :genre %>
	
	<%= f.label :year %>
	<%= f.text_field :year %><br><br>
	
	<h2>Actors</h2>
	<%= f.fields_for :actors do |a| %>
		<%= a.label :name %>
		<%= collection_select(:actors, :id, @all_actors, :id, :name, {}, :multiple => true, :include_blank => true) %><br><br>
	<% end %>
	
	
	<%= f.submit %>
<% end %>

app/views/movies/show.html.erb
<%= image_tag(@movie.image) %> 
<h2><%= @movie.title %></h2>
<p><%= @movie.description %></p>
<p><%= @movie.rating %></p>
<p><%= @movie.genre %></p>
<p><%= @movie.year %></p>



<h3>Cast</h3>
<% if @actors.any? %>
	<% @actors.each do |a| %>
		<%= link_to a.name, a %><br>
	<% end %>
<% end %>

<div style="height:30px;"></div>

<p><%= link_to 'Edit', edit_movie_path, class: 'btn btn-info' %></p>
<p><%= link_to "All Movies", movies_path, class: 'btn btn-primary' %></p>
<p><%= link_to "Delete Movie", movie_path(@movie), method: :delete, data: { confirm: "You really wanna do that huh?" }, class: 'btn btn-danger' %></p>

app/views/shows/edit.html.erb
<%= form_for @show do |f| %>
	
	<%= f.label :name %><br>
	<%= f.text_field :name %><br><br>
	
	<%= f.label :image %><br>
	<%= f.text_field :image %><br><br>
	
	<%= f.label :description %><br>
	<%= f.text_field :description %><br><br>
	
	<%= f.label :genre %><br>
	<%= f.text_field :genre %><br><br>
	
	<%= f.label :rating %><br>
	<%= f.text_field :rating %><br><br>
	
	<%= f.fields_for :actors do |a| %>
		<%= a.text_field :name %>
		<%= a.check_box :_destroy %>
		<%= a.label :_destroy, 'remove' %><br>
	<% end %>
	
	<%= f.submit %>
	
<% end %>

app/views/shows/index.html.erb
<h1>Tv Shows</h1>
<%= link_to 'New Tv Show', new_show_path, class: 'btn btn-primary' %>

<div style="height:30px;"></div>

<div class="row">
<% @shows.each do |show| %>

		<div class="col-sm-6 col-md-3">
			<div class="thumbnail">
				<%= link_to image_tag(show.image), show %>
				<div class="caption">
					<% link_to show.name, show %>
					<% show.actors.each do |a| %>
						<% link_to a.name, a %>
					<% end %>
					<p></p>
				</div>
			</div>
		</div>

<% end %>
</div>

app/views/shows/new.html.erb
<%= form_for @show do |f| %>
	
	<%= f.label :name %><br>
	<%= f.text_field :name %><br><br>
	
	<%= f.label :image %><br>
	<%= f.text_field :image %><br><br>
	
	<%= f.label :description %><br>
	<%= f.text_field :description %><br><br>
	
	<%= f.label :genre %><br>
	<%= f.text_field :genre %><br><br>
	
	<%= f.label :rating %><br>
	<%= f.text_field :rating %>
	
	<h2>Actors</h2>
	<%= f.fields_for :actors do |a| %>
		<%= a.label :name %>
		<%= collection_select(:actors, :id, @all_actors, :id, :name, {}, :multiple => true, :include_blank => true) %><br><br>
	<% end %>
	
	<%= f.submit %>
	
<% end %>

app/views/shows/show.html.erb
<%= image_tag(@show.image) %>
<h1><%= @show.name %></h1>
<p><%= @show.description %></p>
<p><%= @show.rating %></p>
<p><%= @show.genre %></p>


<div>
	<h3>Cast</h3>
	<% if @actors.any? %>
		<% @actors.each do |actor| %>
			<p><%= link_to actor.name, actor %></p>
		<% end %>
	<% end %>
	
</div><br>

<%= link_to 'Edit Show', edit_show_path, class: 'btn btn-info' %>
<%= link_to 'All Tv Shows', shows_path, class: 'btn btn-primary' %>
<%= link_to 'Delete Tv Show', show_path, method: :delete, class: 'btn btn-danger' %>